# Generated by Django 5.2.1 on 2025-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=502)),
                ('slave_id', models.PositiveIntegerField(default=1)),
                ('register_address', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
