# Generated by Django 5.2.1 on 2025-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdevice',
            name='port',
            field=models.PositiveIntegerField(default=5020),
        ),
    ]
