# Generated by Django 5.2.1 on 2025-06-20 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('slave_id', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(247)])),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('mqtt_command_topic', models.CharField(default='mqtt_devices/{serial_number}/command', max_length=255)),
                ('mqtt_status_topic', models.CharField(default='mqtt_devices/{serial_number}/status', max_length=255)),
            ],
        ),
    ]
