# Generated by Django 5.2.1 on 2025-06-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttdevice',
            name='is_paused',
        ),
    ]
